services:
  redis:
    image: redis:7.2
    container_name: redis-local
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data # Lưu dữ liệu vào ổ cứng
    networks:
      - redis_net

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - "5540:5540"
    restart: unless-stopped
    networks:
      - redis_net

networks:
  redis_net:
    driver: bridge

volumes:
  redis_data: # Định nghĩa volume để lưu trữ